name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Version type (patch, minor, or major)'
        required: true
        default: 'patch'
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Validate NPM Token
        if: success()
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "NPM_TOKEN secret is missing. Please configure it in repository secrets."
            exit 1
          fi

      - name: Build
        run: npm run build

      - name: Configure Git
        if: success()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Bump version and push
        if: success()
        run: |
          VERSION_TYPE=${{ github.event.inputs.version-type || 'patch' }}
          NEW_VERSION=$(npm version $VERSION_TYPE --no-git-tag-version)
          git add package.json package-lock.json
          git commit -m "chore: bump version to ${NEW_VERSION}"
          git tag -d ${NEW_VERSION} || true
          git push origin :refs/tags/${NEW_VERSION} || true
          git tag ${NEW_VERSION}
          git push origin main --tags --force

      - name: Publish to npm
        if: success()
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true

      - name: Check publish status
        if: steps.publish.outcome != 'success'
        run: echo "npm publish failed. Check logs for details."